// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IrData } from "./IrData";
import type { IrProcessingConfig } from "./IrProcessingConfig";
import type { ParameterUpdate } from "./ParameterUpdate";

export type InitResponse = { initParams: Array<ParameterUpdate>, irData: IrData | null, config: IrProcessingConfig, };
