[package]
name = "np-fundsp-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
fundsp = "0.20.0"
# thread in debug builds.
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = [
    "assert_process_allocs",
] }
