// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IrData = {
	name: string;
	rawBytes: Array<number>;
	lengthSeconds: number;
	numChannels: number;
	sampleRate: number;
};
