// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterUpdate } from "./ParameterUpdate";

export type Message = { "type": "init" } | { "type": "windowClosed" } | { "type": "resize", "data": { width: number, height: number, } } | { "type": "parameterUpdate", "data": ParameterUpdate } | { "type": "slotUpdate", "data": string };
