// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Parameters = "gain" | "dryWet" | "lowpassEnabled" | "lowpassFreq" | "lowpassQ" | "bellEnabled" | "bellFreq" | "bellQ" | "bellGain" | "highpassEnabled" | "highpassFreq" | "highpassQ";
