// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { Parameter } from '@/lib/parameters';

export type ParameterUpdate = { parameterId: Parameter; value: number };
