// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameters } from "./Parameters";

export type ParameterUpdate<T> = { parameter: Parameters, value: T, };
