// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginParams = { gain: number, dry_wet: number, lowpass_enabled: boolean, lowpass_freq: number, lowpass_q: number, bell_enabled: boolean, bell_freq: number, bell_q: number, bell_gain: number, highpass_enabled: boolean, highpass_freq: number, highpass_q: number, };
